name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"  # Must be at least 2.19.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.2.6
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.2.0
  http: ^0.13.6
  google_generative_ai: ^0.4.7

dependency_overrides:
  http: ^1.1.0  # Force override for google_generative_ai

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/1.png"
  adaptive_icon_foreground: "assets/icons/temp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner_1.jpg
    - assets/images/banner_2.jpg
    - assets/images/profile.jpg
    - assets/icons/cropped_image.png

    # Add more images as needed