name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
    
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  image_picker: ^0.8.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner_1.jpg
    - assets/images/banner_2.jpg
    # Add more images as needed